---
- hosts: localhost
  gather_facts: false
  become_user: root
  tasks:
    - name: Download MySQL Community Repo
      get_url:
        url: http://repo.mysql.com/mysql-community-release-el7-7.noarch.rpm
        dest: /
    - name: Install the Mysql Repo
      command: /usr/bin/rpm -ivh /mysql-community-release-el7-7.noarch.rpm
    - name: create directory 
      command: mkdir /Mysql
    - name: change permission
      file: path=/Mysql mode=777 state=directory
   # - name: copy the rpm from server to clients
   #   copy: src=/root/mysql-5.7.25-1.el7.x86_64.rpm-bundle.tar dest=/
    - name: Install MySql using tar
      unarchive: 
       src: /mysql-5.7.25-1.el7.x86_64.rpm-bundle.tar
       dest: /Mysql
       remote_src: yes
    - name: Find all rpm files in /Mysql folder
      find:
        paths: "/Mysql"
        pattern: "*.rpm"
      register: rpm_files

    - set_fact:
        rpm_list: "{{ rpm_files.files | map(attribute='path') | list}}"

    - name: installing the rpm files
      yum:
        name: "{{rpm_list}}"
        state: present       
     
    - name: Start MySQL Server and enable it
      service: name=mysqld state=started enabled=yes


