---
- hosts: 192.168.1.121
  become: true
  gather_facts: yes
  tasks:
  
  - name: Login to mysql
    shell: mysql -u root -pRoot@123 -e 'create user "neha"@"%" identified with mysql_native_password by "Root@123";'

#  - name: Create a user in Mysql
#    mysql_user:
#     name: bob
#     password: 12345
#     priv: '*.*:ALL'
#     state: present

