---
- hosts: 192.168.1.90
  gather_facts: true
  vars:
    ansible_become: yes
    ansible_become_method: enable
    ansible_user: translab
    ansible_password: cisco
    ansible_become_pass: cisco
    ansible_network_os: ios
    ansible_connection: network_cli
  tasks:
    - cli_command:
        commands: copy flash tftp
        check_all: True
        prompt:
          - Address
          - source file
          - destination
        answer:
          - 192.168.1.107
          - c2960-lanbasek9-mz.150-2.SE8.bin
          - c2960-lanbasek9-mz.150-2.SE8.bin
        vars:
          ansible_command_timeout: 1200
          
      register: config

    - copy:
        content: "{{ config.stdout[0]}}"
        dest: /flash
