---
- hosts: 192.168.1.90                                                       
  gather_facts: false
  vars:
    ansible_become: yes
    ansible_become_method: enable
    ansible_user: translab
    ansible_password: cisco
    ansible_become_pass: cisco
    ansible_network_os: ios
    ansible_connection: network_cli
  tasks:
   - name: port management
     ios_config:
       lines:
        - no shutdown
       parents: interface fastEthernet0/4
     
