---
- hosts: all
  become: true
  become_user: postgres
  tasks:

  - name: create a database
    postgresql_db:
      name: sahis1l
      encoding: UTF-8
      lc_collate: de_DE.UTF-8
      template: template0
      state: present
