---
- hosts: 192.168.1.125
  become: true
  become_user: root
  tasks:
  - name: create mongodb repo file
    command: touch /etc/yum.repos.d/mongodb-org-4.0.repo

  - name: Add content to MongoDB repo file
    blockinfile:
      path: /etc/yum.repos.d/mongodb-org-4.0.repo
      block: |
        [mongodb-org-4.0]
        name=MongoDB Repository
        baseurl=https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/4.0/x86_64/
        gpgcheck=1
        enabled=1
        gpgkey=https://www.mongodb.org/static/pgp/server-4.0.asc

  - name: Install MongoDB
    yum:
      name: mongodb-org
      state: present

  - name: start MongoDB service
    service:
      name: mongod
      state: started
  
  - name: enable mongodb
    service:
      name: mongod
      enabled: yes
  
