---
# create a new VM from a template
- name: VM from template
  hosts: 192.168.1.200
  gather_facts: false
  connection: local
  vars:
    vcenter_hostname: esxidomain
    vcenter_user: root
    vcenter_pass: root@123
    esxhost: 192.168.1.200
    datastore: datastore1
    #vmtemplate: VM01
    name: "newvmcreated"
    folder: /vmfs/volumes/datastore1/
    notes: Ansible Test
    dumpfacts: False
  tasks:
    - name: Create VM
      vmware_guest:
        validate_certs: False
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        esxi_hostname: "{{ esxhost }}"
        folder: "{{ folder }}"
        #datacenter: dc
        name: "{{ name }}"
        #template: "{{ vmtemplate }}"
        disk:
          - size_gb: "{{ disk_size | default(20) }}"
            type: thin
            datastore: "{{ datastore }}"
        networks:
        - name: VM Network
          type: dhcp
        hardware:
          memory_mb: "{{ vm_memory | default(1024) }}"
        wait_for_ip_address: True
        state: present
      register: newvm

    - name: IP address info
      debug:
        msg: "{{ newvm.instance.ipv4 }} {{ name }}"
