---
  - name: Provision an EC2 Instance 
    hosts: localhost
    connection: local
    gather_facts: False
    tags: provisioning

    vars:
      instance_type: t3.xlarge
      security_group: Testsecgrp
      image: ami-01c45f5f0cbe56de4
      region: ap-south-1
      keypair: Ansible
      count: 1
    #vars_files: 
      #- /var/lib/awx/projects/aws/vars/aws_key.yml
    tasks:

      - name: Create New security group with below given name
        local_action:
          module: ec2_group
          #aws_access_key: "{{ aws_access_key }}"
          #aws_secret_key: "{{ aws_secret_key }}"
          name: "{{ security_group }}"
          description: Security Group for Newly Created EC2 Instance
          region: "{{ region }}"
          rules:
            - proto: tcp
              from_port: 3389
              to_port: 3389
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 80
              to_port: 80
              cidr_ip: 0.0.0.0/0
          rules_egress:
            - proto: all
              cidr_ip: 0.0.0.0/0


      - name: Launch the new  EC2 Instance
        local_action: ec2
                      group={{ security_group }}
                      instance_type={{ instance_type}}
                      image={{ image }}
                      wait=true
                      region={{ region }}
                      keypair={{ keypair }}
                      count={{count}}
        register: ec2

      - name: Wait for EC2 Instance to Spin-up and ready for RDP access
        local_action: wait_for
                      host={{ item.public_ip }}
                      port=3389
                      state=started
        with_items: "{{ ec2.instances }}"

      - name: Adding Tags to Identify
        local_action: ec2_tag resource={{ item.id }} region={{ region }} state=present
        with_items: "{{ ec2.instances }}"
        args:
          tags:
            Name: TestSever
            PurPose: Testing EC2 Instance From Ansible
