---
  - hosts: all
    gather_facts: false
    tasks:
       - shell:
            hstname=$(hostname);
            free=$(free -m | grep Mem | awk '{print $7}');
            ps -eo pid,ppid,cmd,%mem,%cpu --sort=-%mem | head >/tmp/top_proccesses_consuming_memory.txt;
            file=/tmp/top_proccesses_consuming_memory.txt;
            memory_usage=`free -m | awk 'NR==2{print $3*100/$2 }'`;
            if [ `echo "${memory_usage} > 2.0" | bc` -eq 1 ];
            then
            echo "$memory_usage memory  utilized on  $hstname" > /home/filelog.txt;
            File=$(cat /home/filelog.txt);
            rm -rf /home/filelog.txt;
            echo $File;
            fi;
         register: result
       - name: send email
         local_action:
           module: mail
           host: smtp.gmail.com
           port: 587
           to: pardeep.singh@translabtechnologies.com
           from: pardeep.singh@translabtechnologies.com
           username: pardeep.singh@translabtechnologies.com
           password: apple@456
           attach:
           - /tmp/top_proccesses_consuming_memory.txt
           timeout: 5
           secure: starttls
           subject: Ansible_Memory ALERT for {{inventory_hostname}}
           body: Warning Memory is  80% utilized -

                 {{result.stdout}}

         when: result.stdout

